### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by VojtaNN** [setnicka/ulozto-downloader#159] opened 2023-04-15 09:37 UTC
[Autodetect] tflite_runtime available, using --auto-captcha
Starting downloading for url 'https://uloz.to/file/RZgKIKeQMKFF/hitler-kaput-gitler-kaput-2008-cz-dabing-mkv'
Getting info (filename, filesize, …)
[TOR]   TOR started
Cannot download file: Uloz.to returned status code 403, error: <!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=7b8334bf2ae8077d')"></div>
        <form id="challenge-form" action="/file/RZgKIKeQMKFF/hitler-kaput-gitler-kaput-2008-cz-dabing-mkv?__cf_chl_f_tk=cocknQbti2mxZ7CEQnZw2UCM6RUhpxKwjCoVqi.qJPQ-1681551405-0-gaNycGzNCpA" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="z7pq1wND.35L.2H7D4KBG8hWTYmb7eV3ucnefM8lQWA-1681551405-0-ASMKZG71DwXjs5Txxj0qHVIOE1U02bRjFrakD6cBiOXkl3IGaLnKTg22khucOeQtI1DePeWCxx_2cjZvoFinwNKphozef9gFJqL25UgCBxzwnP37Ud1O7dxtbxbNttKb2AZHkH0hXKnZc3Dwdxy3GN4YMr9FHJ89Mc4REO6DySnf3WMomuv_AnRTCzkP5diDMRDPObi2KtXZ77w4LXjwxQtk29z7HVfElZl4dV0s51N5iIUCJE1KkFa4Aqb4kHZgnFJsdTyE9gflvaxBMZIP2oa0vaTz-t29yL-43kvfoFF-IHfN0z-cl23L8LqxqS4Fujk-NDvN1RlMSh4Y6aAVQ3oYBE9aAbPOH427cbIAVgHx586sUH2a5PDPthVRYwP6qt2APel-XOTUxy46bjp8bXndh8_-d3Y7ZyC5O4zAuh6abSRS90M-5-J0djzVhF_FsavjIEtMFth9GpZ-GmggzYVr1iJa5X8uCr27EziSlPlJ1nfEjVLF_WqQJjkduh0LgH3wmOWdrmjZL6GSNOnef2N44lLQYyVI4QZDMfXjgfimQxKXR1X7nEiHApHORFHiEySP_yuFJ4At2fZdAtqgMx4qJ68nY_ioTdpMWNug1KhA2FVu4-CJpkzU8r1-JZuzh84rU4hG8vkh2eVSwwiCLUXBqP9S_L9BQe97eai1KsVuiZH-YM18pjy2vPhzN6ZQijUthsw7txZtYeO_BUvmFE5GWQdmFZHdAEjddCmscA7s2F01vMYNRwLDJ3tQ4cSYzhkCvQbbBIxNrK4jztru9LuvBNkIATyG7E4fdBT0f81t7eLztSHhMRo63RtPozZ-9Lldxxy2-5Xh1zsXsqHHfMGyf8xbcE3H8pNRGsYEGkUFY-CHo0UFqjLTodG64ljX4_qcmIWCKcZtQyo-kddQcfpeE2HZ1o97muVo0NKjXZMamWpDU70JixJqb23nuQhzfGv_O33GXc_aVp8ez0sj5CHNld83kGkRBRYO7FvL524v0a41k1UHxBlm7vgp5YHmEc1PpHncUxuQeaYsIJwxAsLEf2IgSYDwQRaLhmwTlWEYEG801YfwHA1PpkLf6x98MAPgjrNm-uFFdodACFzkt5bKyJu43FNKw4dIQ9S8O6N4phGXcOvmmVsxv7Rd4kEBIoLPrxZI_WTobZz7BN3UWvHqhmlCsRFZ-WJ0dZFbCqW_m_-3p33uF_IlqQBSzr5A1oEt0bxeEH0uQGmpAR84GCwIdzZIs72GEHJvaWxwxDqjIpdtgNzewDpOOpHQMTkd_PtsJRN94B6BudT6yNwWTo_gHFQcgWRnYvdXS_7IGN7kGbW508p9Ot-25f8MOpNG_Fs7kDLaUh03BgR2kraLW53N9XTSGSrRu8nkpE_nrUqq1TAnWwTq2vgZT1922p_u5DK1A884As96yn1yLSCmnLFZPbgNIWQqw3Myid6ByjthuwWQcGnfxjDEOp8qFSWJsh1o7bGXXBz5yEdw8HE1OcsCDzJ4GzL5k6ClyAvNBxVLBQy9Xu0fRaKQXeYd8mjiDW7V7bxOqSaZQXIovqS-FfH4JDMnle1jDj3eGkWi1WX2UURHmaxioIyOrPPXdRpCMZIIZI6OAdvT21ilzyo5CWRTU2P36g6yaqSWE1LUV5frZSAMTjdVILbq1jBVrDRHptzGj4PYaZCRABkXViCt_zQNsFet92LfL_KXI6JGKhcbwdGNe-6nBXh-W56z1Qa-yWRrrHxmy8mW_lb44P-5do6DMsKm9EtpCytuy8FfVnNW0W3iNYh9I5mxISvJe2qmUYiyARNw4pMhCv8XnB88jbatICI6nAhvE2hRm581GQ6rSKmvUxutVyyBT5Ydm8JgkaNMFNM446T50jSdT54A6yEhVIbMlZlf3O2pmAgyqhFzL2WN5d0K0ObL36tjwQDWnuAnJGiphP4n3iLFrzKEALik-MxpZoz-MKk5bHuz5i4VI0EoCGCj-_1ypaqkm-pZu0RorNj-IDPnTt7v1_Fx7ishCKm8RmTOu-YJC1gh8pWYoh5Dd2mjCQJbNHWak_O4W2MvvpGTNUpPO68ZTKLO9pk14HSztrVN6Ftl3wuBHrsQlNwqPzPkMpln9KlXdgdv6lPWMNRBYG1ZXZFlf7r_1yCRzHMywQd5Kr3i_F32q01TWljjs38yHx2Ws5mgayZ_uhjNdFAIpyGz2r9KTv6v3tQcFlN8W4P9KEIbLPUY1d8Ef5Yrkm9FPQKJRvISwV-GpoXC2dz4jWHmNinF1yHEkxP5k2VE9CGtJ3q11lMeR4Nsq6NOFlllalGv9DMjoum4UdnP2uqRPxPdCKRVZuqGOnkpgNwIwhhddQKPv6NafDKp-aJ_EJ4xmLwIDcKze5I3Nu0gZRln4c6CKO8a1-WaZ6sFln79e_z6N2-1x7H9jQLMGVxAXxHFQKna9A7aR6x_GScEaOJTnD1BNjtp92CXaBI4vsDw9maVHJPIZaC3WXXNEZxHpVvXU_9yTCENLapoH5XO90g_xklRTHKSyPX-KaXJvbLILiIc2hzhzYun2-gCIyDv3bwYIw9OWUV7Uvho1wqNRTeX4jPMIyp1L0Kztcb43g3OkRk16yQp6smXT1PT0vcN5SVfN0aYAlagqe0M3PPlT-xtJeDx7YiT8hWKInY">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cZone: 'uloz.to',
            cType: 'managed',
            cNounce: '88126',
            cRay: '7b8334bf2ae8077d',
            cHash: '28cbee4a1e84b72',
            cUPMDTk: "\/file\/RZgKIKeQMKFF\/hitler-kaput-gitler-kaput-2008-cz-dabing-mkv?__cf_chl_tk=cocknQbti2mxZ7CEQnZw2UCM6RUhpxKwjCoVqi.qJPQ-1681551405-0-gaNycGzNCpA",
            cFPWv: 'g',
            cTTimeMs: '1000',
            cMTimeMs: '0',
            cTplV: 5,
            cTplB: 'cf',
            cK: "",
            cRq: {
                ru: 'aHR0cHM6Ly91bG96LnRvL2ZpbGUvUlpnS0lLZVFNS0ZGL2hpdGxlci1rYXB1dC1naXRsZXIta2FwdXQtMjAwOC1jei1kYWJpbmctbWt2',
                ra: 'cHl0aG9uLXJlcXVlc3RzLzIuMjguMg==',
                rm: 'R0VU',
                d: '/d6phK3umr+L57Efp8JYC9bRUN8DvFywsXN7jEEdUvb+03vjNhAL9wNm+RogUOzIbmgka0YnmyWjdHTA+G3bEqvWhwyoZLikryl5XvECQIXvWkWeztGvi2SxigpSZmPS7Nd0tC6fvDWKHjVquyQ8LgAzbswtnbqpF5og/1vdM7xUOrTNggfK+fraok3LFVgJzzP63JrP047DA4aRohmqxBoOz+rzN9TPYLkkmwf7cJNCKrYnytL8AIsAEABF9VIH9qu7be3j9siKu8p+tJjWVRvrrZ4B1NnwFqLuaJwKNAbyBoFEeDDozKtipyFM+oHS0lbS1yq689Shp2+/vVGiVRZEbcWbQM3qA2fjqKPoRY4h6Llt/I2TeCVxchKqTRq9XU1abnocJC0Bk9SfYBM3T1CCcHuicL3xkhbhIR7mKUwkDfn7nEy0Farj6RPbOP7VfPCyBeyWZaEuf8KhZTVxknnPj8rz7fD1fKSdMuMsOQt3FhWAtP2d7s1Hi5pkFv4mk6+mykCyR44BT+k4tGJELgdXGdZbncRp5QgCE3DiVKq0jJ1diVGEtKjfkFNUwLm5',
                t: 'MTY4MTU1MTQwNS45NDcwMDA=',
                m: 'xqrV/X87vAfGOzpOw0Lij7KyGF2VRb2IO87yx+8jcDQ=',
                i1: 'zrHAkV24LAjywkIGaRZ1Kg==',
                i2: 'mKZ7w/bGxaUURvkQD0995g==',
                zh: 'H6H5rT46MdJEduO2EFVWUYu6Mz0W/6o6lKBs5jFOnDc=',
                uh: 'neMFmDCz0LRc0/Wea+5x0IhJieHbzcQVSkMgFkgnrjc=',
                hh: 'AZxN1L+Nck6+Yo5cCT418B4s2dJxrgUeCciQcMYDIbA=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=7b8334bf2ae8077d');
        trkjs.setAttribute('alt', '');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/managed/v1?ray=7b8334bf2ae8077d';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/file\/RZgKIKeQMKFF\/hitler-kaput-gitler-kaput-2008-cz-dabing-mkv?__cf_chl_rt_tk=cocknQbti2mxZ7CEQnZw2UCM6RUhpxKwjCoVqi.qJPQ-1681551405-0-gaNycGzNCpA" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

</body>
</html>

Terminating download. Please wait for stopping all threads.
Download terminated.

And error.txt

Apr 15 11:34:43.000 [notice] Tor 0.4.7.13 (git-7c1601fb6edd780f) opening new log file.

**Comment by fighellboy** [comment] 2023-04-16 11:55
some problem..

**Comment by EnhancedMind** [comment] 2023-04-18 22:01
Přepiš `uloz.to` na `zachowajto.pl` v URL, asi nějaká změna na straně uložto a nějaké domény jsou blokované. Je to takový hack ale do opravy asi dostatečný

**Comment by VojtaNN** [comment] 2023-04-27 14:31
> ... už mi tato možnost nefunguje. Asi to stopli.

Mě už taky ne :(

**Comment by setnicka** [comment] 2023-05-02 19:30
Duplicate of #157

**Closed by setnicka** 2023-05-02 19:30 UTC
Labels: duplicate
